### ISSUE TITLE
Can't get :extension: 'yaml' to work

### ISSUE THREAD

**Issue by eefahy** [voxpupuli/hiera-eyaml#106]
My hiera.yaml file is as follows however, encrypted blocks in *.yaml files are not working. Renaming the file to *.eyaml and removing the :extension: 'yaml' line makes everything work just fine. Any pointers on how to debug this?

```

---
:backends:
  - 'yaml'
  - 'eyaml'
:yaml:
  :datadir: "/etc/puppet/%{::environment}/hieradata"
:eyaml:
  :datadir: "/etc/puppet/%{::environment}/hieradata"
  :pkcs7_private_key: '/etc/puppet/keys/private_key.pkcs7.pem'
  :pkcs7_public_key:  '/etc/puppet/keys/public_key.pkcs7.pem'
  :extension: 'yaml'
:hierarchy:
  - "node/%{::clientcert}"
  - 'common'
```

Having the :extension: 'yaml' line in hiera.yaml also appears to break hiera lookups for *.eyaml files so it's doing something I just can't tell what.

**Comment by gdhbashton** [comment]
I had this problem (CentOS 7, Puppet 3.7.4, hiera-eyaml 2.0.6) and the solution is simple - the ordering of the backends in `hiera.conf` is important!

```
:backends:
  - eyaml
  - yaml
```

You must ensure that the `eyaml` backend is listed *before* the `yaml` backend!

Cheers,
Gavin.

**Comment by gtmtech** [comment]
Am I missing something obvious here? Eyaml reads yaml fine, so if you want to use the yaml extension, why use the yaml backend at all? Why not just use the eyaml backend, which will read pure yaml files just fine?

**Comment by gdhbashton** [comment]
@gtmtech That does makes sense, and I was simply following the advice on the homepage of the project.. https://github.com/TomPoulton/hiera-eyaml#hiera - if Tom is recommending both `eyaml` and `yaml` in the hiera config, there's maybe good reason for it.

**Comment by BMourelo** [comment]
On 18/02/15 16:54, gdhbashton wrote:
> @gtmtech <https://github.com/gtmtech> That does makes sense, and I was
> simply following the advice on the homepage of the project..
> https://github.com/TomPoulton/hiera-eyaml#hiera - if Tom is recommending
> both |eyaml| and |yaml| in the hiera config, there's maybe good reason
> for it.
>
It may be for this reason:

Important Note: The eyaml backend will not parse internally json 
formatted yaml files, whereas the regular yaml backend will.

but I think you can not use the same .yaml extension for both.

**Comment by elyscape** [comment]
> but I think you can not use the same .yaml extension for both.

Correct. Hiera uses the file extension to determine which backend to use.

**Comment by TomPoulton** [comment]
The reason for the setup in the README is to (hopefully) make the installation/transition easier for people already using hiera with .yaml files

The best thing to do in my opinion is to only use the .eyaml backend and either change the extension of all .yaml files to .eyaml, or keep everything as .yaml and set the `:extension:` property in hiera.yaml. This is what we do and it removes a lot of complications with the hierarchy. However as @BMourelo says there are some gotchas with this approach which is why it's not the "recommended" setup

**Comment by madAndroid** [comment]
I'm seeing strange symptoms when both `eyaml` and `yaml` backends are configured: the encrypted value is occasionally served into files as is, and sometimes decrypted (and the ordering is correct with `eyaml` preceding `yaml` in the backends key) ... in order to resolve this, I'm considering removing the yaml backend, and only using the eyaml one. 

My concern is the caveat of:

> Important Note: The eyaml backend will not parse internally json formatted yaml files, whereas the regular yaml backend will.

As far as I know, our config doesn't include 'internally json formatted yaml' .. but one exception could be the use of JSON syntax for empty hash keys, which is required when using `create_resources()` with empty hashes - does that count as json formatted yaml? I'm going to attempt removing the regular YAML backend, and hopefully it will resolve my issue - will report back here.

**Comment by madAndroid** [comment]
Please disregard the previous comment - in our use case, we'd incorrectly configured the hiera.yaml.

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer
